"""empty message

Revision ID: 03026661eac3
Revises: 171b137b3ede
Create Date: 2019-12-03 10:53:12.955871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03026661eac3'
down_revision = '171b137b3ede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('is_used', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user', 'is_used')
    # ### end Alembic commands ###
