"""empty message

Revision ID: 112c125dd3a9
Revises: cc793eb7e313
Create Date: 2019-12-03 11:04:01.602987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112c125dd3a9'
down_revision = 'cc793eb7e313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_dict', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pre_ini_data', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_dict', schema=None) as batch_op:
        batch_op.drop_column('pre_ini_data')

    # ### end Alembic commands ###
