"""empty message

Revision ID: 48e7714c543e
Revises: 2d9b3be1bc4e
Create Date: 2019-12-03 09:11:46.741022

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48e7714c543e'
down_revision = '2d9b3be1bc4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_project',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('info', sa.String(length=32), nullable=True),
    sa.Column('uid', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_project_uid'), 't_project', ['uid'], unique=False)
    op.create_table('t_history',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('pid', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('info', sa.String(length=500), nullable=True),
    sa.Column('staus', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('uid', mysql.INTEGER(display_width=11), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['t_project.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_history_pid'), 't_history', ['pid'], unique=False)
    op.create_index(op.f('ix_t_history_uid'), 't_history', ['uid'], unique=False)
    op.create_table('t_sp',
    sa.Column('pid', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('uid', mysql.INTEGER(display_width=11), nullable=False),
    sa.ForeignKeyConstraint(['pid'], ['t_project.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('pid', 'uid')
    )
    op.create_index(op.f('ix_t_sp_uid'), 't_sp', ['uid'], unique=False)
    op.add_column('t_dict', sa.Column('id', mysql.INTEGER(display_width=11), nullable=False))
    op.alter_column('t_dict', 'name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=32),
               nullable=True)
    op.alter_column('t_dict', 'pid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.add_column('t_user', sa.Column('pwd', sa.String(length=32), nullable=True))
    op.add_column('t_user', sa.Column('uname', sa.String(length=32), nullable=True))
    op.alter_column('t_user', 'is_used',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('t_user', 'nick_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('t_user', 'rid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('t_user', 'regis_date')
    op.drop_column('t_user', 'password')
    op.drop_column('t_user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('name', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('t_user', sa.Column('password', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('t_user', sa.Column('regis_date', mysql.DATETIME(), nullable=False))
    op.alter_column('t_user', 'rid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('t_user', 'nick_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('t_user', 'is_used',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('t_user', 'uname')
    op.drop_column('t_user', 'pwd')
    op.alter_column('t_dict', 'pid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('t_dict', 'name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=32),
               nullable=False)
    op.drop_column('t_dict', 'id')
    op.drop_index(op.f('ix_t_sp_uid'), table_name='t_sp')
    op.drop_table('t_sp')
    op.drop_index(op.f('ix_t_history_uid'), table_name='t_history')
    op.drop_index(op.f('ix_t_history_pid'), table_name='t_history')
    op.drop_table('t_history')
    op.drop_index(op.f('ix_t_project_uid'), table_name='t_project')
    op.drop_table('t_project')
    # ### end Alembic commands ###
