"""empty message

Revision ID: 654dfccb3b34
Revises: 
Create Date: 2019-12-03 10:01:31.842177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654dfccb3b34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_dict',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uname', sa.String(length=32), nullable=True),
    sa.Column('nick_name', sa.String(length=32), nullable=True),
    sa.Column('pwd', sa.String(length=32), nullable=True),
    sa.Column('rid', sa.Integer(), nullable=True),
    sa.Column('is_used', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('catgory', sa.String(length=32), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('total_account', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_project_uid'), 't_project', ['uid'], unique=False)
    op.create_table('t_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('info', sa.String(length=500), nullable=True),
    sa.Column('staus', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['t_project.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_history_pid'), 't_history', ['pid'], unique=False)
    op.create_index(op.f('ix_t_history_uid'), 't_history', ['uid'], unique=False)
    op.create_table('t_sp',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pid'], ['t_project.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('pid', 'uid')
    )
    op.create_index(op.f('ix_t_sp_uid'), 't_sp', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_sp_uid'), table_name='t_sp')
    op.drop_table('t_sp')
    op.drop_index(op.f('ix_t_history_uid'), table_name='t_history')
    op.drop_index(op.f('ix_t_history_pid'), table_name='t_history')
    op.drop_table('t_history')
    op.drop_index(op.f('ix_t_project_uid'), table_name='t_project')
    op.drop_table('t_project')
    op.drop_table('t_user')
    op.drop_table('t_dict')
    # ### end Alembic commands ###
