"""empty message

Revision ID: 96abb0fab3ef
Revises: 112c125dd3a9
Create Date: 2019-12-03 11:05:09.921702

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96abb0fab3ef'
down_revision = '112c125dd3a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_dict', schema=None) as batch_op:
        batch_op.drop_column('pre_ini_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_dict', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pre_ini_data', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
