"""empty message

Revision ID: 9f4498a1b659
Revises: 96abb0fab3ef
Create Date: 2019-12-03 11:06:23.809747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f4498a1b659'
down_revision = '96abb0fab3ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opa_time', sa.DateTime(), nullable=True))

    with op.batch_alter_table('t_project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pre_end_data', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('pre_ini_data', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rea_end_data', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rea_ini_data', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_project', schema=None) as batch_op:
        batch_op.drop_column('rea_ini_data')
        batch_op.drop_column('rea_end_data')
        batch_op.drop_column('pre_ini_data')
        batch_op.drop_column('pre_end_data')

    with op.batch_alter_table('t_history', schema=None) as batch_op:
        batch_op.drop_column('opa_time')

    # ### end Alembic commands ###
