"""empty message

Revision ID: cc793eb7e313
Revises: 03026661eac3
Create Date: 2019-12-03 10:59:18.785167

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc793eb7e313'
down_revision = '03026661eac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_project', schema=None) as batch_op:
        batch_op.alter_column('catgory',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=33),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_project', schema=None) as batch_op:
        batch_op.alter_column('catgory',
               existing_type=sa.String(length=33),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)

    # ### end Alembic commands ###
