"""empty message

Revision ID: ffd00c01d39f
Revises: 
Create Date: 2019-12-03 12:57:06.703670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffd00c01d39f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_dict',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uname', sa.String(length=32), nullable=True),
    sa.Column('nick_name', sa.String(length=32), nullable=True),
    sa.Column('pwd', sa.String(length=32), nullable=True),
    sa.Column('rid', sa.Integer(), nullable=True),
    sa.Column('is_used', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('catgory', sa.String(length=33), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('pre_ini_data', sa.DateTime(), nullable=True),
    sa.Column('rea_ini_data', sa.DateTime(), nullable=True),
    sa.Column('pre_end_data', sa.DateTime(), nullable=True),
    sa.Column('rea_end_data', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('total_account', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('t_project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_project_uid'), ['uid'], unique=False)

    op.create_table('t_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('info', sa.String(length=500), nullable=True),
    sa.Column('staus', sa.Integer(), nullable=True),
    sa.Column('opa_time', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['t_project.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('t_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_history_pid'), ['pid'], unique=False)
        batch_op.create_index(batch_op.f('ix_t_history_uid'), ['uid'], unique=False)

    op.create_table('t_sp',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pid'], ['t_project.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('pid', 'uid')
    )
    with op.batch_alter_table('t_sp', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_sp_uid'), ['uid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_sp', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_sp_uid'))

    op.drop_table('t_sp')
    with op.batch_alter_table('t_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_history_uid'))
        batch_op.drop_index(batch_op.f('ix_t_history_pid'))

    op.drop_table('t_history')
    with op.batch_alter_table('t_project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_project_uid'))

    op.drop_table('t_project')
    op.drop_table('t_user')
    op.drop_table('t_dict')
    # ### end Alembic commands ###
